"use client"
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components_/header";
import { Toaster } from "@/components/ui/toaster";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { UpdateCartContext } from "./context/UpdateCartContext";
import {PageLoading } from "./loading/pageloading";
import { LoadingContext } from "./context/PageLoadingContext";

const roboto = Roboto({ subsets: ["latin"], weight: ['100', '300', '500', '700']});

// export const metadata: Metadata = {
//   title: "Akrpharma",
//   description: "Generated by L_A project",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const params = usePathname();
  const [updateCart, setUpdateCart]=useState(false);
  const showHeader = params === '/sign-in' || params === '/register' ?false:true;
  const [isLoading, setLoading] = useState(false);

  return (
    <html lang="en">
      <body className={roboto.className}>
        <LoadingContext.Provider value={{ isLoading, setLoading }}>
            <UpdateCartContext.Provider value={{ updateCart, setUpdateCart }}>
              {isLoading && <PageLoading />}
              {showHeader && <Header />}
              {children}
              <Toaster />
            </UpdateCartContext.Provider>
        </LoadingContext.Provider>
        <script src="https://cdn.botpress.cloud/webchat/v1/inject.js"></script>
        <script src="https://mediafiles.botpress.cloud/4bb300b0-8e4a-404b-8056-105992920c8c/webchat/config.js" defer></script>
      </body>
    </html>
  );
}
